### ISSUE TITLE
Conditional

### ISSUE THREAD

**Issue by mantielero** [sealmove/binarylang#10]
Is there a way to make conditional parsing? Something equivalent to [switch-on](https://doc.kaitai.io/user_guide.html#switch-advanced) in kaitai.

**Comment by sealmove** [comment]
@mantielero yes. Please take a look at [operations](https://sealmove.github.io/binarylang/#dsl-operations) and [this closed issue](https://github.com/sealmove/binarylang/issues/4). Hopefully such an example will be added to the [Tutorial](https://sealmove.github.io/binarylang/tutorial.html).

**Comment by arkanoid87** [comment]
I've upgraded my code to binarylang 1.0 and now the same operation is
```nim
template peekcondget*(parse, parsed, output, prefix: untyped) =
    let save = s.getPosition
    let peek = s.readStr(8*prefix.len)
    s.setPosition(save)
    if peek == prefix:
        parse
        output = parsed

template peekcondput*(encode, encoded, output, prefix: untyped) =
    if not encoded.isNil:
        output = encoded
        encode
```

**Comment by sealmove** [comment]
@arkanoid87 and others, please feel free to make PRs for adding such plugins.
