### ISSUE TITLE
Use value-based "object" instead of "ref object" by default

### ISSUE THREAD

**Issue by Yardanico** [sealmove/binarylang#13]
Right now binarylang generates a ref type for the parser to store data in. I think that ref types are not needed in most of cases as they're allocated on the heap and are also ref-counted. 

So I propose to make types "object" by default, with an option like `isRef`  for the parser so that then the type becomes `ref object`. I don't know what stability guarantees does binarylang have, and if it's undesirable to break existing code (that does `echo data.toType()[]` for example, `isObj` can be added instead.

**Comment by arkanoid87** [comment]
I've been dealing with same problem here https://github.com/sealmove/binarylang/issues/12, where I've been using custom `==` equality operator to restore old tuple-based return types.
I'm not sure if objects are better than ref objects in this context as I'm quite happy with the current solution, but I think that docoded objects from same stream should be considered equal.

**Comment by sealmove** [comment]
Thanks again for the suggestion. Default is now non-ref. I added the parser option `reference` which accepts the values `y` and `n`.
