### ISSUE TITLE
Byte endianess for subparsers

### ISSUE THREAD

**Issue by arkanoid87** [sealmove/binarylang#14]
Documentation says that byte endianness can only be used with multiple byte-long integers, so the correct endianess is applied only for integers multiple of 8bits.
This works nicely but doesn't apply for subparsers that are actually multiple of 8bits, forcing me to not use subparsers but grab instead the captured int32/64 (that is being read with correct endianess) turn it into a string and push it into a new parser, turning a possibly elegant solution into a chain of get/put with decode/encode and int to string transform in the middle.

Is there a better solution for this?

**Comment by sealmove** [comment]
Um... you know that you can [specify endianness for the whole parser](https://sealmove.github.io/binarylang/#dsl-invocation-parser-options), right?

**Comment by arkanoid87** [comment]
let's say you have a GPS that sends data in big-endian byte order and the specs says
```
int32_t:
    latitude: 24 bits
    orientation: 8bits
int32_t:
    longitude: 24 bits
    velocity: 8bits
```
you can't do
```nim
struct(gpsdata, endian = l):
    u24: latitude
    u8: orientation
    u24: longitude
    u8: velocity
```
as byte endianess would be applied only to latitude and longitude, and not to (latitude+orientation) and (longitude+velocity).
Using subparsers as in:
```nim
struct(gpslatitude, endian = b):
    u24: latitude
    u8: orientation

struct(gpslongitude, endian = b):
    u24: longitude
    u8: velocity

struct(gpsdata, endian = l):
    *gpslatitude: latitude
    *gpslongitude: longitude
```
Is not a solutions as again the byte endianess would be wrong and out of specs. The only right solution would be to use the full type size and apply decoding later on, as in:
```nim
struct(gpsdata, endian = l):
    u32: latitude_pack
    u32: longitude_pack

# --------------------------

struct(gpslatitude, endian = b):
    u24: latitude
    u8: orientation

struct(gpslongitude, endian = b):
    u24: longitude
    u8: velocity
```

**Comment by sealmove** [comment]
Thanks for the explanation. Okay I understand now. 

Well, your data fundamentally need to be parsed twice. The data transmission is the first step, and uses little-endian. The decoding is a second step, and uses big-endian. I don't think giving the notion of endianness to struct parsers can solve your problem. In fact, I really can't see how endianness for struct parsers could make any sense.

Indeed the *proper* solution is the one you chose; treating each 32-bit gps data elements as substreams, and pushing them to a different parser.

That being said, although not a scalable solution, for this particular problem you can just figure out the layout manually and make a spec that combines the data transmission endianness with the data layout endianness. Simply changing the order of the fields and using big-endian should work:
```nim
struct(gpslatitude):
  u8: orientation
  u24: latitude

struct(gpslongitude):
  u8: velocity
  u24: longitude

struct(gpsdata):
  *gpslatitude: latitude
  *gpslongitude: longitude
```
