### ISSUE TITLE
Proposal of struct size getter

### ISSUE THREAD

**Issue by arkanoid87** [sealmove/binarylang#17]
It would be convenient to have a way to get the total size of a struct parser at compile time

something like:
```nim
struct(myparser):
  u1: flag1
  u2: flag2
  u4: field1
  u4: field2
  u13: field3

const packetsize = myparser.encodedsize # 24 bits
```

**Comment by sealmove** [comment]
This can be achieved with [substreams](https://sealmove.github.io/binarylang/#features-substreams):
```nim
struct(aux):
  u1: flag1
  u2: flag2
  u4: field1
  u4: field2
  u13: field3

struct(myparser):
  *aux(3)
```

I don't intent to add any kind of sugar syntax for this, because I think substreams is an elegant and scalable solution which is also general enough to cover other use cases.

**Comment by arkanoid87** [comment]
after rewiring my code I now see how a future implementation of SocketBitStream would solve this problem the right way, as encoded struct size is only used when alternating binarylang with manual handling of socket recv
