### ISSUE TITLE
Repetition until end of message

### ISSUE THREAD

**Issue by bluemax75** [sealmove/binarylang#2]
I'm trying to parse a protocol (COPS) that has a message header with the message size, and then includes a list of objects. Each object specifies it's own size in the object header.
How can I get the object list?

**Comment by bluemax75** [comment]
From a test example I found that the condition s.atEnd may be used for this

```nim
createParser(copsHeader):
  u4: version = 1
  u4: flags
  u8: opcode
  u16: clientType
  u32: msgLength

createParser(copsobj):
  u16: length
  u8: cnum 
  u8: ctype
  u8: content[length - 4]

createParser(copsmsg):
  *copsHeader: header
  # The following is a list of copsobj that is read until the stream s ends
  *copsobj: objlist{s.atEnd}
```

**Comment by sealmove** [comment]
Sorry for not answering. So `s.atEnd` solves your problem, right?

**Comment by bluemax75** [comment]
Hi. Using s.atEnd it works correctly. You may close the issue
