### ISSUE TITLE
Struct with Bitfields

### ISSUE THREAD

**Issue by TurtleP** [sealmove/binarylang#21]
Hi,

I'm currently trying to parse a file format and verify its header content. However, the header has three fields in it which are bitfields. I've tried looking at the documentation, but I haven't found anything that could help as of yet.

**Comment by sealmove** [comment]
Hi. Can you provide a concrete example? Bitfields are not any different from other fields in binarylang since fields are described in bits instead of bytes. For example you can write:

```nim
struct(parser):
  6: x
```

which is a bitfield that consists of 6 bits. Of course you must be precise with _bit endianness_ and alignment (please refer to https://sealmove.github.io/binarylang/#features-alignment).

**Comment by TurtleP** [comment]
Yeah I had three fields which were bitfields and I had some help figuring out how to get it working properly. It was a bit annoying, though, as I couldn't do the same syntax as in C. 

```c
struct A
{
  uint8_t  yeet: 3
  uint32_t code
};```

Having the ability to say it's a u8 with a 3-bit bit field would have saved me some time, given all the other fields were easily the same size as would be in C.

**Comment by sealmove** [comment]
The resulting type is the smallest nim type that fits the field. In your case it's `uint8` as you want. In my example:

```nim
struct(parser):
  6: x
```

you will actually get an object field `x` of type `uint8`.

**Comment by TurtleP** [comment]
Right, which is what I had initially, but because the fields were bitfields I [had to do this](https://github.com/TurtleP/t3xview/blob/master/source/header.nim) which wasn't exactly ideal, as it would have been easier to access them as bitfields normally.

**Comment by sealmove** [comment]
Ok I see now, the semantics are different from C bitfields. This is a design decision. The merit is explicitness. In your example you are being explicit about the discarded bit.
