### ISSUE TITLE
Fixing hints, or not?

### ISSUE THREAD

**Issue by arkanoid87** [sealmove/binarylang#24]
What's the author position about this?

![image](https://user-images.githubusercontent.com/1446586/200341703-a5855660-a06a-4493-9eae-9bd11a227835.png)

**Comment by sealmove** [comment]
Hello. Thanks for reporting. Could you provide more information about the origin of these warning?

**Comment by arkanoid87** [comment]
Bummer! It seems that might be a consequence of a macro going wild. Let me triple check what's going on here one more time

**Comment by arkanoid87** [comment]
Nervemind! My fault. It was just a silly mistake. Closing!
