### ISSUE TITLE
Error converting to binary and back

### ISSUE THREAD

**Issue by bluemax75** [sealmove/binarylang#29]
I'm starting to test the module and I needed to use the following struct:

```Nim
struct(avpHeader):
  u32: code
  u8: flags
  u24: length
  u32 : vendorId
```

Creating an example object, converting to binary and back I get a zero in the length field
This is the example code (I used print module to easily print values):

```Nim
import binarylang, bitstreams
import print, strutils

struct(avpHeader):
  u32: code
  u8: flags
  u24: length
  u32 : vendorId

var a = AvpHeader(code: 2, flags: 1, length: 23, vendorId: 12)
var s = newStringBitStream()
avpheader.put(s, a)
print a
s.seek(0)
print avpheader.get(s)
```

I was not able to understand where's the problem

**Comment by sealmove** [comment]
Hello @bluemax75 and thank you for reporting this! It turns out there was a bug in the bitstream library. left shift was used instead of right shift. Fixed https://github.com/sealmove/bitstreams/commit/bd5718bd00d78c71b3ef9e48bf968d55d8912ff2.
