### ISSUE TITLE
Emit parser type of tupleMeat

### ISSUE THREAD

**Issue by arkanoid87** [sealmove/binarylang#3]
I was dealing with this problem https://play.nim-lang.org/#ix=2SpD and IRC community helped me adding the output type to the createParser macro.

```
  let tName = ident(($name).capitalizeAscii)
  result = quote do:
    type `tName` = `tupleMeat`
    proc `readerName`(`bs`: BitStream): `tupleMeat` =
      `reader`
    proc `writerName`(`bs`: BitStream, `input`: `tupleMeat`) =
      `writer`
    let `name` = (get: `readerName`, put: `writerName`)
```
It works nicely and only requires parser name to be lowercase, what do you think about adding this to binarylang?

**Comment by sealmove** [comment]
@arkanoid87 thanks for the issue. Not a bad idea but the `typeGetter` macro has served me well so far. Your idea creates some limitations as you pointed out, for example I always have my parsers capitalized. I think it's an unnecessary breaking change.

**Comment by arkanoid87** [comment]
I really like typeGetter, it was just undocumented feature! It works perfectly, thanks!

**Comment by sealmove** [comment]
Oh, you are right! I didn't realize it's not mentioned in README.md; I'll add it, thanks!
