### ISSUE TITLE
VariantParser and shared attributes

### ISSUE THREAD

**Issue by arkanoid87** [sealmove/binarylang#5]
I 've tested the new VariantParser and it works nicely! Problem is that it shares same limitation of objects variants: it can't contain shared attributes between types.

There are ongoing discussions on this: https://github.com/nim-lang/RFCs/issues/19

I could circumvent the problem by moving the shared parts to custom parser or other structs, but I wonder if there's some sugar to enable this already with binarylang in an elegant way.

```nim
mport std/[sugar]
import binarylang

type VariantKind = enum
    vkOne,
    vkTwo

createVariantParser(variantParser, disc: VariantKind):
    (vkOne):
        s: foo(3) = "foo"
        s: other
    (vkTwo):
        s: bar(3) = "bar"
        s: other

let data = "foo12345"
let parsed = VariantParser.get(newStringBitStream(data), vkOne)
dump parsed.repr

# Error: attempt to redefine: 'other'
```

**Comment by sealmove** [comment]
It is especially important to keep the *stream* -> *nim internal representation* mapping obvious. Implementation details are important. The user must know that `createVariantParser` declares an object variant type, and he should know exactly how this type looks like. I can't think of a way to add such sugar without hiding implementation details or without adding an extra mental step for figuring it out.

**Comment by ajusa** [comment]
This is honestly something that is really tricky. I (as a user) think that the current way of not being able to have the same field name across two different "kind"s is bad. Like really bad for anyone who is used to similar types in a different language. I also think that this really isn't up to binarylang to solve, it is an issue for that RFC. This issue should probably be left open until that RFC is resolved though, as there are enough people who want some sort of solution to fix the problem, there just isn't consensus on what the best way is.

**Comment by sealmove** [comment]
BinaryLang's union is modeled on Nim's object variant. If Nim supports shared field name, so will BinaryLang; otherwise it will not. I don't intent to deviate from Nim semantics for this.
