### ISSUE TITLE
Which things should be exported?

### ISSUE THREAD

**Issue by ajusa** [sealmove/binarylang#9]
If the object is public, we probably want to export the to/from helper procs.
I'll update this later if I get time with discussion about the different ways you can export fields/procs.

**Comment by sealmove** [comment]
Fixed by 3760b1d306af8b35838ac6d93e8f2d213203fb67. We should keep this issue open though, to discuss exportation in general.

**Comment by sealmove** [comment]
Exportation is now controlled with the `visibility` [parser option](https://sealmove.github.io/binarylang/#dsl-invocation-parser-options). More fine-grained control does not seem useful enough, so I believe it's better to keep the dsl design.
